feat: style operations in search item component
Redocly/portal-default-theme pull request #7
Opened 2022-04-19 17:32 UTC by ohorbachevskyi

## What/Why/How?
This PR adds additional styling into search result item of ref docs operation.

## Screenshots (optional)
<img width="672" alt="Screenshot 2022-04-21 at 15 44 24" src="https://user-images.githubusercontent.com/17987710/164463998-a1995c7d-639f-4e70-9f20-967c0bf13e55.png">
<img width="745" alt="Screenshot 2022-04-21 at 15 21 34" src="https://user-images.githubusercontent.com/17987710/164464004-d08e57a1-897c-47ed-bb41-b4e3871a515f.png">

## Check yourself

- [ ] Code is linted
- [ ] Tested
- [ ] All new/updated code is covered with tests

## Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

2022-04-19 17:36 UTC, ozapotichnyi requested changes

2022-04-19 17:36 UTC, ozapotichnyi commented on src/Search/SearchItem.tsx
> +        {item.httpVerb && <Badge type={item.httpVerb}>{item.httpVerb}</Badge>}
```suggestion
        {item.httpVerb ? <Badge type={item.httpVerb}>{item.httpVerb}</Badge> : null}
```

2022-04-19 17:36 UTC, ozapotichnyi commented on src/Search/SearchItem.tsx
> +        {item.place && (item.place + ' > ')}
What's place?
Can we push it in path?

2022-04-19 17:36 UTC, ozapotichnyi commented on src/Search/SearchItem.tsx
> +        {item.place && (item.place + ' > ')}
Or concat before?

2022-04-26 08:59 UTC, slavikbez approved these changes

2022-04-26 09:00 UTC, slavikbez commented on src/Search/SearchItem.tsx
> +  line-height: 22px;
I believe there are css variables from `font-size` and `line-height` properties. Try to use them

2022-04-26 09:56 UTC, ozapotichnyi requested changes

2022-04-26 09:56 UTC, ozapotichnyi commented on src/Search/SearchItem.tsx
> +      </Operaition>
I'd hide operation for regular text results (Mardkdown):
```suggestion
      {item.httpVerb ? <Operaition>
          <OperationBadge type={item.httpVerb}>{item.httpVerb}</OperationBadge> 
          {highlight(item.pathName)}
        </Operaition>
      : null}
```

2022-04-26 09:56 UTC, ozapotichnyi commented on src/Search/SearchItem.tsx
> +        </Parameters>
Let's extract it into separate component
```suggestion
        <Parameters parameters={item.parameters} />
```

2022-04-26 13:39 UTC, ozapotichnyi commented on src/Search/Parameters.tsx
> +  }
const moreItems = Math.max(0, parameters.length - MAX_ITEMS)

2022-04-26 13:40 UTC, ozapotichnyi commented on src/Search/Parameters.tsx
> +  }
```suggestion
  const moreItems = Math.max(0, parameters.length - MAX_ITEMS)
```

2022-04-26 13:40 UTC, ozapotichnyi approved these changes

2022-04-26 14:22 UTC, merged